spring.application.name=idea-forge-api

spring.datasource.url=jdbc:postgresql://localhost:5432/idea_forge
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true